/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dad8e7',
        'sky-blue': '#C6DEF1',
        'on-secondary-container': '#67645c',
        background: '#fbf8ff',
        'on-secondary-fixed-variant': '#49473f',
        'primary-fixed-dim': '#bfc2ff',
        'on-tertiary-container': '#ffc8ba',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e9e6f5',
        'on-background': '#1a1b25',
        'primary-fixed': '#e0e0ff',
        'on-surface': '#1a1b25',
        'tertiary-container': '#ae2900',
        'tertiary-fixed': '#ffdbd2',
        outline: '#757588',
        lavender: '#E2CFEA',
        'inverse-surface': '#2f2f3b',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#1d1c15',
        'inverse-primary': '#bfc2ff',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f1effe',
        'surface-bright': '#fbf8ff',
        primary: '#0200e7',
        'surface-container-highest': '#e3e1f0',
        'on-error': '#ffffff',
        'on-surface-variant': '#454557',
        'on-primary-fixed-variant': '#0b0de9',
        'on-primary-container': '#cfd0ff',
        'on-tertiary-fixed': '#3c0800',
        'outline-variant': '#c6c4da',
        'on-error-container': '#93000a',
        tertiary: '#841d00',
        'honey-yellow': '#FAEDCB',
        surface: '#fbf8ff',
        'surface-variant': '#e3e1f0',
        'secondary-container': '#e8e2d7',
        'primary-container': '#3139fb',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'surface-tint': '#353dfe',
        'flamingo-pink': '#FFC2D1',
        'on-primary-fixed': '#00006e',
        'tertiary-fixed-dim': '#ffb4a1',
        'sage-green': '#C9E4DE',
        'sidebar-charcoal': '#1A1A1A',
        'surface-container-low': '#f5f2ff',
        'secondary-fixed-dim': '#cbc6bc',
        secondary: '#615e56',
        'on-tertiary-fixed-variant': '#891e00',
        'canvas-warm': '#F8F2E7',
        'on-primary': '#ffffff',
        'secondary-fixed': '#e8e2d7',
        'surface-container': '#eeecfb',
      },
      spacing: {
        'sidebar-width': '280px',
        'bento-gutter': '24px',
        'container-margin': '40px',
        'widget-padding': '32px',
      },
      fontFamily: {
        'headline-lg': ['Bricolage Grotesque', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Space Mono', 'monospace'],
        'display-lg': ['Bricolage Grotesque', 'sans-serif'],
        'headline-xl': ['Bricolage Grotesque', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      boxShadow: {
        'panel-soft': '0 40px 60px rgba(0,0,0,0.1)',
        'card-soft': '0 40px 60px rgba(0,0,0,0.05)',
        'card-pink': '0 40px 60px rgba(255,194,209,0.2)',
        'card-blue': '0 40px 60px rgba(198,222,241,0.2)',
        'card-green': '0 40px 60px rgba(201,228,222,0.2)',
        'card-purple': '0 40px 60px rgba(226,207,234,0.2)',
        'card-yellow': '0 40px 60px rgba(250,237,203,0.2)',
      },
    },
  },
  plugins: [],
};
